2019-03-11 14:00:09,174 - Common.py[line:34] - INFO: 失败原因：
2019-03-11 14:00:09,190 - Common.py[line:35] - INFO: [Errno 2] No such file or directory: 'E:/python/LDA_model/Data/test.xlx'
2019-03-11 19:05:28,349 - Common.py[line:78] - INFO: 失败原因：
2019-03-11 19:05:28,389 - Common.py[line:79] - INFO: 'NoneType' object has no attribute 'span'
2019-03-11 19:06:22,856 - Common.py[line:77] - INFO: 失败原因：
2019-03-11 19:06:22,857 - Common.py[line:78] - INFO: 'NoneType' object has no attribute 'span'
2019-03-12 10:17:29,987 - Common.py[line:71] - INFO: 失败原因：
2019-03-12 10:17:30,018 - Common.py[line:72] - INFO: No engine for filetype: ''
2019-03-12 10:38:55,461 - Common.py[line:57] - INFO: 失败原因：
2019-03-12 10:38:55,527 - Common.py[line:58] - INFO: Wrong number of items passed 0, placement implies 1
2019-03-12 11:01:28,128 - Common.py[line:126] - INFO: 失败原因：
2019-03-12 11:01:28,144 - Common.py[line:127] - INFO: 'NoneType' object has no attribute 'group'
2019-03-12 11:02:09,921 - Common.py[line:126] - INFO: 失败原因：
2019-03-12 11:02:09,921 - Common.py[line:127] - INFO: 'NoneType' object has no attribute 'group'
2019-03-12 17:11:52,327 - Common.py[line:114] - INFO: 失败原因：
2019-03-12 17:11:52,327 - Common.py[line:114] - INFO: 失败原因：
2019-03-12 17:11:52,358 - Common.py[line:115] - INFO: 'NoneType' object has no attribute 'group'
2019-03-12 17:11:52,358 - Common.py[line:115] - INFO: 'NoneType' object has no attribute 'group'
2019-03-12 17:13:16,867 - Common.py[line:114] - INFO: 失败原因：
2019-03-12 17:13:16,867 - Common.py[line:114] - INFO: 失败原因：
2019-03-12 17:13:16,867 - Common.py[line:115] - INFO: 'NoneType' object has no attribute 'group'
2019-03-12 17:13:16,867 - Common.py[line:115] - INFO: 'NoneType' object has no attribute 'group'
2019-03-12 17:16:45,481 - Common.py[line:114] - INFO: 失败原因：
2019-03-12 17:16:45,481 - Common.py[line:114] - INFO: 失败原因：
2019-03-12 17:16:45,481 - Common.py[line:115] - INFO: 'NoneType' object has no attribute 'group'
2019-03-12 17:16:45,481 - Common.py[line:115] - INFO: 'NoneType' object has no attribute 'group'
2019-03-12 20:05:10,184 - Common.py[line:115] - INFO: 失败原因：
2019-03-12 20:05:10,184 - Common.py[line:115] - INFO: 失败原因：
2019-03-12 20:05:10,416 - Common.py[line:116] - INFO: 'NoneType' object has no attribute 'group'
2019-03-12 20:05:10,416 - Common.py[line:116] - INFO: 'NoneType' object has no attribute 'group'
2019-03-12 20:14:18,884 - Common.py[line:119] - INFO: 失败原因：
2019-03-12 20:14:18,884 - Common.py[line:119] - INFO: 失败原因：
2019-03-12 20:14:18,884 - Common.py[line:120] - INFO: search() missing 1 required positional argument: 'string'
2019-03-12 20:14:18,884 - Common.py[line:120] - INFO: search() missing 1 required positional argument: 'string'
2019-03-13 10:45:47,867 - Common.py[line:36] - INFO: 失败原因：
2019-03-13 10:45:47,867 - Common.py[line:36] - INFO: 失败原因：
2019-03-13 10:45:47,899 - Common.py[line:37] - INFO: [Errno 2] No such file or directory: 'E:/python/LDA_model/Data\\test.xlsx.xlsx'
2019-03-13 10:45:47,899 - Common.py[line:37] - INFO: [Errno 2] No such file or directory: 'E:/python/LDA_model/Data\\test.xlsx.xlsx'
2019-03-14 16:31:09,861 - Common.py[line:158] - INFO: 失败原因：
2019-03-14 16:31:09,861 - Common.py[line:158] - INFO: 失败原因：
2019-03-14 16:31:09,942 - Common.py[line:159] - INFO: Illegal chunk pattern: {<VBG|VBZ>?<DT|CD>?<JJ|JJR|JJS|>*<NN|NNS|NNP|NNPS>+<<CC><NN|NNS|NNP|NNPS>>?<VBG>?}
2019-03-14 16:31:09,942 - Common.py[line:159] - INFO: Illegal chunk pattern: {<VBG|VBZ>?<DT|CD>?<JJ|JJR|JJS|>*<NN|NNS|NNP|NNPS>+<<CC><NN|NNS|NNP|NNPS>>?<VBG>?}
2019-03-15 15:03:10,873 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:03:10,873 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:03:10,873 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:03:10,873 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:03:10,873 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:03:10,904 - Main.py[line:101] - INFO: 'numpy.int32' object is not callable
2019-03-15 15:03:10,904 - Main.py[line:101] - INFO: 'numpy.int32' object is not callable
2019-03-15 15:03:10,904 - Main.py[line:101] - INFO: 'numpy.int32' object is not callable
2019-03-15 15:03:10,904 - Main.py[line:101] - INFO: 'numpy.int32' object is not callable
2019-03-15 15:03:10,904 - Main.py[line:101] - INFO: 'numpy.int32' object is not callable
2019-03-15 15:08:10,733 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:08:10,733 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:08:10,733 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:08:10,733 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:08:10,733 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:08:10,733 - Main.py[line:101] - INFO: 'int' object is not iterable
2019-03-15 15:08:10,733 - Main.py[line:101] - INFO: 'int' object is not iterable
2019-03-15 15:08:10,733 - Main.py[line:101] - INFO: 'int' object is not iterable
2019-03-15 15:08:10,733 - Main.py[line:101] - INFO: 'int' object is not iterable
2019-03-15 15:08:10,733 - Main.py[line:101] - INFO: 'int' object is not iterable
2019-03-15 15:09:04,636 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:09:04,636 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:09:04,636 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:09:04,636 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:09:04,636 - Main.py[line:100] - INFO: 失败原因：
2019-03-15 15:09:04,636 - Main.py[line:101] - INFO: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:09:04,636 - Main.py[line:101] - INFO: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:09:04,636 - Main.py[line:101] - INFO: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:09:04,636 - Main.py[line:101] - INFO: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:09:04,636 - Main.py[line:101] - INFO: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:22:41,879 - NlpPreProcess.py[line:56] - INFO: 失败原因：
2019-03-15 15:22:41,879 - NlpPreProcess.py[line:56] - INFO: 失败原因：
2019-03-15 15:22:41,879 - NlpPreProcess.py[line:56] - INFO: 失败原因：
2019-03-15 15:22:41,879 - NlpPreProcess.py[line:56] - INFO: 失败原因：
2019-03-15 15:22:41,879 - NlpPreProcess.py[line:56] - INFO: 失败原因：
2019-03-15 15:22:41,879 - NlpPreProcess.py[line:57] - INFO: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:22:41,879 - NlpPreProcess.py[line:57] - INFO: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:22:41,879 - NlpPreProcess.py[line:57] - INFO: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:22:41,879 - NlpPreProcess.py[line:57] - INFO: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:22:41,879 - NlpPreProcess.py[line:57] - INFO: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:24:06,386 - NlpPreProcess.py[line:56] - INFO: 失败原因：
2019-03-15 15:24:06,386 - NlpPreProcess.py[line:56] - INFO: 失败原因：
2019-03-15 15:24:06,386 - NlpPreProcess.py[line:56] - INFO: 失败原因：
2019-03-15 15:24:06,386 - NlpPreProcess.py[line:56] - INFO: 失败原因：
2019-03-15 15:24:06,386 - NlpPreProcess.py[line:56] - INFO: 失败原因：
2019-03-15 15:24:06,386 - NlpPreProcess.py[line:57] - INFO: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:24:06,386 - NlpPreProcess.py[line:57] - INFO: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:24:06,386 - NlpPreProcess.py[line:57] - INFO: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:24:06,386 - NlpPreProcess.py[line:57] - INFO: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:24:06,386 - NlpPreProcess.py[line:57] - INFO: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2019-03-15 15:24:43,289 - NlpPreProcess.py[line:86] - INFO: 失败原因：
2019-03-15 15:24:43,289 - NlpPreProcess.py[line:86] - INFO: 失败原因：
2019-03-15 15:24:43,289 - NlpPreProcess.py[line:86] - INFO: 失败原因：
2019-03-15 15:24:43,289 - NlpPreProcess.py[line:86] - INFO: 失败原因：
2019-03-15 15:24:43,289 - NlpPreProcess.py[line:86] - INFO: 失败原因：
2019-03-15 15:24:43,289 - NlpPreProcess.py[line:87] - INFO: 'NlpPreProcess' object has no attribute 'stoplist'
2019-03-15 15:24:43,289 - NlpPreProcess.py[line:87] - INFO: 'NlpPreProcess' object has no attribute 'stoplist'
2019-03-15 15:24:43,289 - NlpPreProcess.py[line:87] - INFO: 'NlpPreProcess' object has no attribute 'stoplist'
2019-03-15 15:24:43,289 - NlpPreProcess.py[line:87] - INFO: 'NlpPreProcess' object has no attribute 'stoplist'
2019-03-15 15:24:43,289 - NlpPreProcess.py[line:87] - INFO: 'NlpPreProcess' object has no attribute 'stoplist'
2019-03-15 15:26:00,425 - NlpPreProcess.py[line:86] - INFO: 失败原因：
2019-03-15 15:26:00,425 - NlpPreProcess.py[line:86] - INFO: 失败原因：
2019-03-15 15:26:00,425 - NlpPreProcess.py[line:86] - INFO: 失败原因：
2019-03-15 15:26:00,425 - NlpPreProcess.py[line:86] - INFO: 失败原因：
2019-03-15 15:26:00,425 - NlpPreProcess.py[line:86] - INFO: 失败原因：
2019-03-15 15:26:00,425 - NlpPreProcess.py[line:87] - INFO: dictionary update sequence element #0 has length 1; 2 is required
2019-03-15 15:26:00,425 - NlpPreProcess.py[line:87] - INFO: dictionary update sequence element #0 has length 1; 2 is required
2019-03-15 15:26:00,425 - NlpPreProcess.py[line:87] - INFO: dictionary update sequence element #0 has length 1; 2 is required
2019-03-15 15:26:00,425 - NlpPreProcess.py[line:87] - INFO: dictionary update sequence element #0 has length 1; 2 is required
2019-03-15 15:26:00,425 - NlpPreProcess.py[line:87] - INFO: dictionary update sequence element #0 has length 1; 2 is required
